name: ${COMPOSE_PROJECT_NAME}
services:
    server:
        container_name: ${COMPOSE_PROJECT_NAME}-server
        restart: unless-stopped
        build:
            dockerfile: ./server/Dockerfile
        env_file:
            - ./.env
        ports:
            - 8080:8080
#            - 50000:50000
        volumes:
            - ./server/casc.yaml:/var/casc.yaml
            # Windows
            - server-data:/var/jenkins_home
            # Other
            # - ./server/data:/var/jenkins_home
#            - /var/run/docker.sock:/var/run/docker.sock
    dotnet:
        container_name: ${COMPOSE_PROJECT_NAME}-agent-dotnet
        restart: unless-stopped
        build:
            dockerfile: ./agent-dotnet/Dockerfile
        entrypoint: bash /home/jenkins/startup.sh
        depends_on:
            - server
        environment:
            JENKINS_NODE_HELPER_ID: ${JENKINS_NODE_HELPER_ID}
            JENKINS_NODE_HELPER_PASSWORD: ${JENKINS_NODE_HELPER_PASSWORD}
            JENKINS_AGENT_NAME: ${JENKINS_AGENT_NAME_DOTNET}
            JENKINS_AGENT_WORKDIR: /home/jenkins/agent
            JENKINS_WEB_SOCKET: true
            JENKINS_URL: ${JENKINS_URL}
        volumes:
            - ./agent-dotnet/startup.sh:/home/jenkins/startup.sh
            # Windows
            - agent-dotnet-data:/home/jenkins/agent
            # Other
            # - ./agent-dotnet/data:/home/jenkins/agent
    sonarqube:
        container_name: ${COMPOSE_PROJECT_NAME}-sonarqube
        image: sonarqube:community
        restart: unless-stopped
        depends_on:
            - sonarqube_database
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://sonarqube_database:5432/sonarqube
            SONAR_JDBC_USERNAME: ${SONARQUBE_POSTGRES_USER}
            SONAR_JDBC_PASSWORD: ${SONARQUBE_POSTGRES_PASSWORD}
        ports:
            - 9000:9000
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_temp:/opt/sonarqube/temp
    sonarqube_database:
        container_name: ${COMPOSE_PROJECT_NAME}-sonarqube-database
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${SONARQUBE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${SONARQUBE_POSTGRES_PASSWORD}
            POSTGRES_DB: ${SONARQUBE_POSTGRES_DB}
        volumes:
            - sonarqube_database:/var/lib/postgresql
            - sonarqube_database_data:/var/lib/postgresql/data

# Windows WSL has an issue sharing files between host and container, adding latency to the file system.
# Creating Volumes and mounting them to the container is a workaround.
volumes:
    server-data:
    agent-dotnet-data:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    sonarqube_temp:
    sonarqube_database:
    sonarqube_database_data:

